<?php

namespace WarMachineBundle\Repository;

/**
 * AllianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllianceRepository extends \Doctrine\ORM\EntityRepository
{
}
