<?php

namespace WarMachineBundle\Repository;

/**
 * CorporationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporationRepository extends \Doctrine\ORM\EntityRepository
{
}
