<?php

namespace WarMachineBundle\Repository;

/**
 * KillMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KillMailRepository extends \Doctrine\ORM\EntityRepository
{
}
