<?php

namespace WarMachineBundle\Repository;

/**
 * KillerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KillerRepository extends \Doctrine\ORM\EntityRepository
{
}
