<?php

namespace WarMachineBundle\Repository;

/**
 * LossRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LossRepository extends \Doctrine\ORM\EntityRepository
{
}
