<?php

namespace WarMachineBundle\Repository;

/**
 * VictimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VictimRepository extends \Doctrine\ORM\EntityRepository
{
}
