<?php

namespace WarMachineBundle\Repository;

/**
 * WarActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarActorRepository extends \Doctrine\ORM\EntityRepository
{
}
