<?php

namespace WarMachineBundle\Repository;

/**
 * WarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarRepository extends \Doctrine\ORM\EntityRepository
{
}
